export const manifest = {
	appDir: "_app",
	assets: new Set(["android-chrome-192x192.png","android-chrome-512x512.png","apple-touch-icon.png","embed.png","favicon-16x16.png","favicon-32x32.png","favicon.ico","favicon.svg","logo-192.png","logo-512.png","manifest-orig.json","maskable-192.png","maskable-512.png","media/comptia-blogpost/m1-headers-1.png","media/comptia-blogpost/m1-headers-2.png","media/comptia-blogpost/m1-headers-3.png","media/comptia-blogpost/m1-headers-4.png","media/comptia-blogpost/m1-osi-model-data.png","media/comptia-blogpost/m1-osi-model-pizza.png","media/comptia-blogpost/m1-ports-and-protocols-1.png","media/comptia-blogpost/m1-ports-and-protocols-2.png","media/comptia-blogpost/m1-ports-and-protocols-3.png","media/comptia-blogpost/m2-advance-filtering.png","media/comptia-blogpost/m2-collision-vs-broadcast-domains-1.png","media/comptia-blogpost/m2-collision-vs-broadcast-domains-2.png","media/comptia-blogpost/m2-collision-vs-broadcast-domains-3.png","media/comptia-blogpost/m2-collision-vs-broadcast-domains-4.png","media/comptia-blogpost/m2-dmz.png","media/comptia-blogpost/m2-hub.png","media/comptia-blogpost/m2-intrusion1.png","media/comptia-blogpost/m2-intrusion2.png","media/comptia-blogpost/m2-proxy.png","media/comptia-blogpost/m2-router.png","media/comptia-blogpost/m2-switch.png","media/comptia-blogpost/m2-vpn.png","media/comptia-blogpost/m8-antenna-types-1.png","media/comptia-blogpost/m8-antenna-types-2.png","media/comptia-blogpost/m8-antenna-types-3.png","media/comptia-blogpost/m8-antenna-types-4.png","media/comptia-blogpost/m8-antenna-types-5.png","media/comptia-blogpost/m8-autonomous-vs-lightweight-aps.png","media/comptia-blogpost/m8-channel-bonding-1.png","media/comptia-blogpost/m8-channel-bonding-2.png","media/comptia-blogpost/m8-extender.png","media/comptia-blogpost/m8-infrastructure.png","media/comptia-blogpost/m8-mu-mimo.png","media/comptia-blogpost/m8-non-overlapping-5gh.png","media/comptia-blogpost/m8-non-overlapping.png","media/comptia-blogpost/m8-ofdma-2.png","media/comptia-blogpost/m8-ofdma.png","media/comptia-blogpost/m8-wifi-dsss.png","media/comptia-blogpost/m8-wifi-fdm.png","media/comptia-blogpost/m8-wifi-ortho.png","media/comptia-blogpost/m8-wifi-qam.png","media/comptia-blogpost/m8-wifi-standards.png","media/comptia-blogpost/m9-apipa.png","media/comptia-blogpost/m9-ipv4-pert2.png","media/comptia-blogpost/m9-ipv4-unicast.png","media/comptia-blogpost/m9-ipv4.png","media/comptia-blogpost/m9-subnetting-2.png","media/comptia-blogpost/m9-subnetting-3.png","media/comptia-blogpost/m9-subnetting-calc.png","media/comptia-blogpost/m9-subnetting.png","media/comptia-blogpost/m9-wifi-2.4ghz-channels.png","media/comptia-blogpost/m9-wifi-5ghz-channels.png","media/open-in-new.svg","media/projects/portfolio-site-2021/cover.png","media/projects/portfolio-site-2021/link-preview.png","media/projects/type-kana/select-kana.mov","media/projects/type-kana/session.jpg","media/projects/type-kana/session.mov","media/tombstone.svg","site.webmanifest"]),
	mimeTypes: {".png":"image/png",".ico":"image/vnd.microsoft.icon",".svg":"image/svg+xml",".json":"application/json",".mov":"video/quicktime",".jpg":"image/jpeg",".webmanifest":"application/manifest+json"},
	_: {
		entry: {"file":"start-000ac774.js","js":["start-000ac774.js","chunks/vendor-4b328d4a.js"],"css":[]},
		nodes: [
			() => import('./nodes/0.js'),
			() => import('./nodes/1.js'),
			() => import('./nodes/2.js'),
			() => import('./nodes/3.js'),
			() => import('./nodes/4.js'),
			() => import('./nodes/5.js'),
			() => import('./nodes/6.js'),
			() => import('./nodes/7.js'),
			() => import('./nodes/8.js'),
			() => import('./nodes/9.js'),
			() => import('./nodes/10.js'),
			() => import('./nodes/11.js'),
			() => import('./nodes/12.js'),
			() => import('./nodes/13.js'),
			() => import('./nodes/14.js'),
			() => import('./nodes/15.js'),
			() => import('./nodes/16.js'),
			() => import('./nodes/17.js'),
			() => import('./nodes/18.js'),
			() => import('./nodes/19.js'),
			() => import('./nodes/20.js'),
			() => import('./nodes/21.js'),
			() => import('./nodes/22.js'),
			() => import('./nodes/23.js'),
			() => import('./nodes/24.js'),
			() => import('./nodes/25.js'),
			() => import('./nodes/26.js'),
			() => import('./nodes/27.js'),
			() => import('./nodes/28.js'),
			() => import('./nodes/29.js'),
			() => import('./nodes/30.js'),
			() => import('./nodes/31.js'),
			() => import('./nodes/32.js'),
			() => import('./nodes/33.js'),
			() => import('./nodes/34.js'),
			() => import('./nodes/35.js'),
			() => import('./nodes/36.js'),
			() => import('./nodes/37.js'),
			() => import('./nodes/38.js'),
			() => import('./nodes/39.js')
		],
		routes: [
			{
				type: 'page',
				id: "",
				pattern: /^\/$/,
				names: [],
				types: [],
				path: "/",
				shadow: null,
				a: [0,2],
				b: [1]
			},
			{
				type: 'endpoint',
				id: "sitemap.xml",
				pattern: /^\/sitemap\.xml$/,
				names: [],
				types: [],
				load: () => import('./entries/endpoints/sitemap.xml.ts.js')
			},
			{
				type: 'page',
				id: "playground",
				pattern: /^\/playground\/?$/,
				names: [],
				types: [],
				path: "/playground",
				shadow: null,
				a: [0,3],
				b: [1]
			},
			{
				type: 'page',
				id: "about",
				pattern: /^\/about\/?$/,
				names: [],
				types: [],
				path: "/about",
				shadow: null,
				a: [0,4],
				b: [1]
			},
			{
				type: 'page',
				id: "about/HiddenText",
				pattern: /^\/about\/HiddenText\/?$/,
				names: [],
				types: [],
				path: "/about/HiddenText",
				shadow: null,
				a: [0,5],
				b: [1]
			},
			{
				type: 'endpoint',
				id: "about/selectable",
				pattern: /^\/about\/selectable\/?$/,
				names: [],
				types: [],
				load: () => import('./entries/endpoints/about/selectable.ts.js')
			},
			{
				type: 'endpoint',
				id: "about/cipher",
				pattern: /^\/about\/cipher\/?$/,
				names: [],
				types: [],
				load: () => import('./entries/endpoints/about/cipher.ts.js')
			},
			{
				type: 'endpoint',
				id: "blog.json",
				pattern: /^\/blog\.json$/,
				names: [],
				types: [],
				load: () => import('./entries/endpoints/blog/index.json.ts.js')
			},
			{
				type: 'page',
				id: "blog",
				pattern: /^\/blog\/?$/,
				names: [],
				types: [],
				path: "/blog",
				shadow: null,
				a: [0,6],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-nine-building-applications-vue-nuxt",
				pattern: /^\/blog\/week-nine-building-applications-vue-nuxt\/?$/,
				names: [],
				types: [],
				path: "/blog/week-nine-building-applications-vue-nuxt",
				shadow: null,
				a: [0,7],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-ten-production-grade-vue-part-2",
				pattern: /^\/blog\/week-ten-production-grade-vue-part-2\/?$/,
				names: [],
				types: [],
				path: "/blog/week-ten-production-grade-vue-part-2",
				shadow: null,
				a: [0,8],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-eleven-complete-intro-react",
				pattern: /^\/blog\/week-eleven-complete-intro-react\/?$/,
				names: [],
				types: [],
				path: "/blog/week-eleven-complete-intro-react",
				shadow: null,
				a: [0,9],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-twelve-functional-js-part-1",
				pattern: /^\/blog\/week-twelve-functional-js-part-1\/?$/,
				names: [],
				types: [],
				path: "/blog/week-twelve-functional-js-part-1",
				shadow: null,
				a: [0,10],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-nine-production-grade-vue",
				pattern: /^\/blog\/week-nine-production-grade-vue\/?$/,
				names: [],
				types: [],
				path: "/blog/week-nine-production-grade-vue",
				shadow: null,
				a: [0,11],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-ten-advanced-vue-features",
				pattern: /^\/blog\/week-ten-advanced-vue-features\/?$/,
				names: [],
				types: [],
				path: "/blog/week-ten-advanced-vue-features",
				shadow: null,
				a: [0,12],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-ten-vuex-for-intermediate",
				pattern: /^\/blog\/week-ten-vuex-for-intermediate\/?$/,
				names: [],
				types: [],
				path: "/blog/week-ten-vuex-for-intermediate",
				shadow: null,
				a: [0,13],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-three-intro-linux-command",
				pattern: /^\/blog\/week-three-intro-linux-command\/?$/,
				names: [],
				types: [],
				path: "/blog/week-three-intro-linux-command",
				shadow: null,
				a: [0,14],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-four-intro-to-serverless",
				pattern: /^\/blog\/week-four-intro-to-serverless\/?$/,
				names: [],
				types: [],
				path: "/blog/week-four-intro-to-serverless",
				shadow: null,
				a: [0,15],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-six-code-transformation",
				pattern: /^\/blog\/week-six-code-transformation\/?$/,
				names: [],
				types: [],
				path: "/blog/week-six-code-transformation",
				shadow: null,
				a: [0,16],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-twelve-web-performance",
				pattern: /^\/blog\/week-twelve-web-performance\/?$/,
				names: [],
				types: [],
				path: "/blog/week-twelve-web-performance",
				shadow: null,
				a: [0,17],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-three-intro-dev-tools",
				pattern: /^\/blog\/week-three-intro-dev-tools\/?$/,
				names: [],
				types: [],
				path: "/blog/week-three-intro-dev-tools",
				shadow: null,
				a: [0,18],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-five-hard-parts-ooj",
				pattern: /^\/blog\/week-five-hard-parts-ooj\/?$/,
				names: [],
				types: [],
				path: "/blog/week-five-hard-parts-ooj",
				shadow: null,
				a: [0,19],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-eight-css-in-depth",
				pattern: /^\/blog\/week-eight-css-in-depth\/?$/,
				names: [],
				types: [],
				path: "/blog/week-eight-css-in-depth",
				shadow: null,
				a: [0,20],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/vue-mastery-vue3-forms",
				pattern: /^\/blog\/vue-mastery-vue3-forms\/?$/,
				names: [],
				types: [],
				path: "/blog/vue-mastery-vue3-forms",
				shadow: null,
				a: [0,21],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-eleven-full-stack",
				pattern: /^\/blog\/week-eleven-full-stack\/?$/,
				names: [],
				types: [],
				path: "/blog/week-eleven-full-stack",
				shadow: null,
				a: [0,22],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-nine-intro-to-vue",
				pattern: /^\/blog\/week-nine-intro-to-vue\/?$/,
				names: [],
				types: [],
				path: "/blog/week-nine-intro-to-vue",
				shadow: null,
				a: [0,23],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-six-js-hard-parts",
				pattern: /^\/blog\/week-six-js-hard-parts\/?$/,
				names: [],
				types: [],
				path: "/blog/week-six-js-hard-parts",
				shadow: null,
				a: [0,24],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-twelve-typescript",
				pattern: /^\/blog\/week-twelve-typescript\/?$/,
				names: [],
				types: [],
				path: "/blog/week-twelve-typescript",
				shadow: null,
				a: [0,25],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-two-accessibility",
				pattern: /^\/blog\/week-two-accessibility\/?$/,
				names: [],
				types: [],
				path: "/blog/week-two-accessibility",
				shadow: null,
				a: [0,26],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-two-js-functional",
				pattern: /^\/blog\/week-two-js-functional\/?$/,
				names: [],
				types: [],
				path: "/blog/week-two-js-functional",
				shadow: null,
				a: [0,27],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-five-js-testing",
				pattern: /^\/blog\/week-five-js-testing\/?$/,
				names: [],
				types: [],
				path: "/blog/week-five-js-testing",
				shadow: null,
				a: [0,28],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-five-debugging",
				pattern: /^\/blog\/week-five-debugging\/?$/,
				names: [],
				types: [],
				path: "/blog/week-five-debugging",
				shadow: null,
				a: [0,29],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-four-nodejs-v2",
				pattern: /^\/blog\/week-four-nodejs-v2\/?$/,
				names: [],
				types: [],
				path: "/blog/week-four-nodejs-v2",
				shadow: null,
				a: [0,30],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-one-javascript",
				pattern: /^\/blog\/week-one-javascript\/?$/,
				names: [],
				types: [],
				path: "/blog/week-one-javascript",
				shadow: null,
				a: [0,31],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-seven-deep-js",
				pattern: /^\/blog\/week-seven-deep-js\/?$/,
				names: [],
				types: [],
				path: "/blog/week-seven-deep-js",
				shadow: null,
				a: [0,32],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-four-api-dev",
				pattern: /^\/blog\/week-four-api-dev\/?$/,
				names: [],
				types: [],
				path: "/blog/week-four-api-dev",
				shadow: null,
				a: [0,33],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-one-webdev",
				pattern: /^\/blog\/week-one-webdev\/?$/,
				names: [],
				types: [],
				path: "/blog/week-one-webdev",
				shadow: null,
				a: [0,34],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-three-seo",
				pattern: /^\/blog\/week-three-seo\/?$/,
				names: [],
				types: [],
				path: "/blog/week-three-seo",
				shadow: null,
				a: [0,35],
				b: [1]
			},
			{
				type: 'page',
				id: "blog/week-one-css",
				pattern: /^\/blog\/week-one-css\/?$/,
				names: [],
				types: [],
				path: "/blog/week-one-css",
				shadow: null,
				a: [0,36],
				b: [1]
			},
			{
				type: 'endpoint',
				id: "blog/[slug]/related.json",
				pattern: /^\/blog\/([^/]+?)\/related\.json$/,
				names: ["slug"],
				types: [null],
				load: () => import('./entries/endpoints/blog/_slug_/related.json.ts.js')
			},
			{
				type: 'endpoint',
				id: "work.json",
				pattern: /^\/work\.json$/,
				names: [],
				types: [],
				load: () => import('./entries/endpoints/work/index.json.ts.js')
			},
			{
				type: 'page',
				id: "work",
				pattern: /^\/work\/?$/,
				names: [],
				types: [],
				path: "/work",
				shadow: null,
				a: [0,37],
				b: [1]
			},
			{
				type: 'page',
				id: "work/portfolio-site",
				pattern: /^\/work\/portfolio-site\/?$/,
				names: [],
				types: [],
				path: "/work/portfolio-site",
				shadow: null,
				a: [0,38],
				b: [1]
			},
			{
				type: 'page',
				id: "work/type-kana",
				pattern: /^\/work\/type-kana\/?$/,
				names: [],
				types: [],
				path: "/work/type-kana",
				shadow: null,
				a: [0,39],
				b: [1]
			},
			{
				type: 'endpoint',
				id: "work/[slug]/related.json",
				pattern: /^\/work\/([^/]+?)\/related\.json$/,
				names: ["slug"],
				types: [null],
				load: () => import('./entries/endpoints/work/_slug_/related.json.ts.js')
			}
		],
		matchers: async () => {
			
			return {  };
		}
	}
};
